import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TOOLS = ROOT / "tools" / "cl_midi_network"


class MidiNetworkToolsTests(unittest.TestCase):
    def test_guardian_uses_bonjour_and_coremidi(self):
        source = (TOOLS / "CLMIDINetworkGuardian.m").read_text()
        self.assertIn("MIDINetworkSession", source)
        self.assertIn("netServiceName", source)
        self.assertIn("addConnection", source)
        self.assertNotIn("osascript", source)

    def test_round_trip_ignores_immediate_coremidi_local_echoes(self):
        source = (TOOLS / "CLMIDIRoundTripTester.m").read_text()
        self.assertIn("minimumReturnLatencyMs = 35.0", source)
        self.assertIn("IGNORED_LOCAL_ECHO", source)
        self.assertIn("ignored_local_echoes=", source)
        self.assertIn("latencyMs < minimumReturnLatencyMs", source)

    def test_simulator_echoes_only_program_changes(self):
        source = (TOOLS / "CLYamahaConsoleSimulator.m").read_text()
        self.assertIn("(status & 0xF0) == 0xC0", source)
        self.assertIn("MIDISend", source)
        self.assertIn("program + 1", source)
        self.assertIn("RTP session endpoints unavailable", source)
        self.assertIn("findEndpoint", source)
        self.assertIn("consumeSelfEcho", source)
        self.assertIn("IGNORED_SELF_ECHO", source)
        self.assertIn("CLSentHistorySize = 64", source)
        self.assertIn("age <= 2.0", source)
        self.assertIn("pendingConfirmations[16][128]", source)
        self.assertIn("CLMaxPendingConfirmations = 32", source)
        self.assertIn("CLMaxReceivedPerSecond = 64", source)
        self.assertIn("ECHO_CIRCUIT_OPEN", source)
        self.assertIn("COALESCED_DUPLICATE", source)
        self.assertIn("SUPPRESSED_PENDING_CONFIRMATION", source)
        self.assertNotIn("selfEchoBudget", source)
        self.assertIn('containsString:@"RTPResponder"', source)
        self.assertIn('containsString:@"RTP Receiver"', source)
        build = (TOOLS / "build.sh").read_text()
        self.assertIn("CLMIDIRTPResponder", build)
        self.assertIn("CLMIDIRTPAgent", build)
        agent = (TOOLS / "CLMIDIRTPAgent.m").read_text()
        self.assertIn("NSHost.currentHost.localizedName", agent)

    def test_round_trip_tester_sends_and_matches_the_selected_channel(self):
        source = (TOOLS / "CLMIDIRoundTripTester.m").read_text()
        self.assertIn('@"--channel"', source)
        self.assertIn('expectedChannel - 1', source)
        self.assertIn('== expectedChannel', source)
        self.assertIn('SENT channel=%u', source)
        self.assertIn('observation_ms=500', source)
        self.assertIn('matchingReturnCount > 4', source)
        self.assertIn('totalProgramChangeCount > 16', source)
        self.assertIn('totalProgramChangeCount <= 16', source)
        self.assertIn('LOOP_DETECTED', source)

    def test_build_script_targets_native_tools(self):
        source = (TOOLS / "build.sh").read_text()
        self.assertIn('${1:-$SCRIPT_DIR/build}', source)
        self.assertIn("-framework CoreMIDI", source)
        self.assertIn("-arch arm64 -arch x86_64", source)
        self.assertEqual(source.count("-mmacosx-version-min=10.15"), 7)
        self.assertIn("CLMIDINetworkGuardian", source)
        self.assertIn("CLYamahaConsoleSimulator", source)
        self.assertIn("CLMIDIRoundTripTester", source)
        self.assertIn("CLMIDINetworkDashboard", source)
        self.assertIn("CLYamahaSimulatorDashboard", source)

    def test_dashboard_exposes_visible_rtp_status_and_real_round_trip(self):
        source = (TOOLS / "CLMIDINetworkDashboard.m").read_text()
        self.assertIn('title:@"RTP HORS LIGNE"', source)
        self.assertIn('title:@"RTP DISPONIBLE"', source)
        self.assertIn('title:@"RTP VALIDÉ"', source)
        self.assertIn('CLMIDIRoundTripTester', source)
        self.assertIn('@"--endpoint"', source)
        self.assertIn('@"--program"', source)
        self.assertIn('@"--channel"', source)
        self.assertIn('@"CL5 · Ch.1"', source)
        self.assertIn('@"QL1 · Ch.2"', source)
        self.assertIn('latency_ms=', source)
        self.assertIn('BOUCLE MIDI DÉTECTÉE', source)
        self.assertIn('désactivez Entrée RTP > Piste', source)
        self.assertNotIn('Routages actifs : Aucun · une seule paire RTP', source)
        self.assertIn('DÉMARRER LE SIMULATEUR DISTANT', source)
        self.assertIn('ARRÊTER LE SIMULATEUR DISTANT', source)
        self.assertIn('cl-midi-rtp-control', source)
        self.assertIn('start-simulator', source)
        self.assertIn('stop-simulator', source)
        self.assertIn('50022', source)
        self.assertIn('loopDetectedEndpoint', source)
        self.assertIn('MIDINetworkSession', source)
        self.assertIn('open_rtp_settings.applescript', source)
        self.assertIn('_apple-midi._udp.', source)
        self.assertIn('preferredRtpPeer', source)
        self.assertIn('paradis_latin_logo.jpg', source)
        self.assertIn('accentButton:', source)
        self.assertIn('CL MIDI NETWORK ASSISTANT', source)
        self.assertIn('CL AUDIO · MIDI NETWORK · 2026', source)
        self.assertIn('stylePopup:', source)
        self.assertIn('connect_rtp_peer.applescript', source)
        self.assertIn('executeAndReturnError', source)
        simulator_method = source.split('- (void)startSimulator:', 1)[1].split('- (BOOL)applicationShouldTerminateAfterLastWindowClosed:', 1)[0]
        self.assertIn('Démarrer le simulateur sur l’autre Mac ?', simulator_method)
        self.assertIn('sendto(', simulator_method)
        self.assertIn('Aucune réponse de l’agent RTP distant', simulator_method)
        self.assertNotIn('tell application', simulator_method)
        connect_method = source.split('- (void)connectSelectedPeer:', 1)[1].split('- (void)refreshEndpoints', 1)[0]
        self.assertNotIn('/usr/bin/osascript', connect_method)
        self.assertNotIn('dispatch_get_global_queue', connect_method)
        self.assertNotIn('pkill', source)

    def test_rtp_settings_script_finds_the_network_globe_by_accessibility_text(self):
        source = (TOOLS / "open_rtp_settings.applescript").read_text()
        self.assertIn("entire contents of toolbar 1", source)
        self.assertIn("Bouton globe Réseau MIDI introuvable", source)
        self.assertIn('perform action "AXPress"', source)
        self.assertIn("checkbox 2 of group 1 of group 4", source)

    def test_dashboard_is_a_network_only_technical_panel(self):
        source = (TOOLS / "CLMIDINetworkDashboard.m").read_text()
        self.assertIn('@"DIAGNOSTIC RÉSEAU MIDI"', source)
        self.assertIn('@"SESSION RTP OBSERVÉE"', source)
        self.assertIn('@"PORTS COREMIDI"', source)
        self.assertIn('@"CORRESPONDANTS BONJOUR"', source)
        self.assertNotIn('toggleNetworkSession:', source)
        self.assertNotIn('changeConnectionPolicy:', source)
        self.assertNotIn('session.networkPort', source)
        self.assertIn('session.connections.count', source)
        self.assertIn('EndpointNames(YES)', source)
        self.assertIn('EndpointNames(NO)', source)
        self.assertIn('MIDIInputPortCreate', source)
        self.assertIn('CLPassiveReturnRead', source)
        self.assertIn('queueReturnedProgram:', source)
        self.assertIn('/private/tmp/CL_MIDI_Console_State.json', source)
        self.assertIn('@"program": self.lastCL5Program >= 0 ? @(self.lastCL5Program + 1)', source)
        self.assertIn('@"program": self.lastQL1Program >= 0 ? @(self.lastQL1Program + 1)', source)
        self.assertIn('@"received_at": self.lastCL5ProgramAt', source)
        self.assertIn('@"received_at": self.lastQL1ProgramAt', source)
        self.assertNotIn('MIDISend(', source)
        self.assertNotIn('RETOURS CONSOLES', source)
        self.assertIn('CL_MIDI_Console_State.json', source)
        self.assertNotIn('ltc_timecode', source)
        self.assertIn('@"Mode spectacle"', source)
        self.assertIn('@"Panneau complet"', source)
        self.assertIn('setContentSize:NSMakeSize(500, 430)', source)
        self.assertIn('self.technicalPanel.hidden = self.showModeEnabled', source)
        self.assertIn('RÉSEAUX CONSOLES', source)
        self.assertIn('self.lastCL5Test', source)
        self.assertIn('self.lastQL1Test', source)
        self.assertNotIn('MIDINetworkSession.defaultSession.enabled = YES', source)
        self.assertNotIn('Activer la session', source)
        self.assertNotIn('Accès : aucun', source)
        self.assertNotIn('toggleNetworkSession:', source)
        self.assertNotIn('changeConnectionPolicy:', source)
        self.assertIn('Activation et autorisations gérées dans Réglages de réseau MIDI macOS', source)
        self.assertIn('Réglages : gérés par macOS', source)
        self.assertIn('Validation : test aller-retour', source)
        self.assertIn('ensureGuardianRunning', source)
        self.assertIn('@"CLMIDINetworkGuardian"', source)
        self.assertIn('@[@"--peer-name", peer, @"--interval", @"2"]', source)
        self.assertIn('if (self.guardianTask.running) [self.guardianTask terminate]', source)
        self.assertIn('ensureLegacyWakeIfNeeded', source)
        self.assertIn('@"reconnect_legacy_rtp.applescript"', source)
        self.assertIn('Session RTP historique réveillée', source)

    def test_dashboard_adopts_the_real_discovered_machine_name(self):
        source = (TOOLS / "CLMIDINetworkDashboard.m").read_text()
        self.assertIn("selected = names.firstObject", source)
        self.assertIn('removeObjectForKey:@"preferredRtpPeer"', source)
        self.assertIn("NSHost.currentHost.localizedName", source)
        self.assertIn("[available removeObject:computerName]", source)
        self.assertNotIn("if (selected.length && ![available containsObject:selected]) [available addObject:selected]", source)
        self.assertIn("CL5 and QL1 remain MIDI channel labels", source)

    def test_yamaha_simulator_dashboard_supports_independent_consoles(self):
        source = (TOOLS / "CLYamahaSimulatorDashboard.m").read_text()
        self.assertIn('＋ Ajouter une console', source)
        self.assertIn('CL CONSOLE SIMULATOR', source)
        self.assertIn('Tout démarrer', source)
        self.assertIn('Tout arrêter', source)
        self.assertIn('CL5', source)
        self.assertIn('QL1', source)
        self.assertIn('@"--endpoint"', source)
        self.assertIn('@"--channel"', source)
        self.assertIn('@"--delay-ms"', source)
        self.assertIn('self.rows.count >= 6', source)
        self.assertIn('CLYamahaSimulatorConsoles', source)
        self.assertIn('saveConfiguration', source)

    def test_configurable_reconnect_targets_one_exact_peer(self):
        source = (TOOLS / "connect_rtp_peer.applescript").read_text()
        self.assertIn('peerName', source)
        self.assertIn('__CL_PEER__', source)
        self.assertNotIn('peerName is "__CL_PEER__"', source)
        self.assertIn('Correspondant RTP introuvable', source)
        self.assertIn('Correspondant RTP ambigu', source)
        self.assertIn('click connectButton', source)
        self.assertIn('participantOutline', source)
        self.assertIn('already-connected:', source)
        self.assertIn('checkbox 2 of group 1 of group 4 of toolbar 1', source)
        self.assertIn('networkButtonHelp does not contain "réseau"', source)
        self.assertNotIn('QL1', source)
        self.assertNotIn('click button "Se déconnecter"', source)

    def test_rtp_settings_opener_targets_midi_network_not_avb_browser(self):
        source = (TOOLS / "open_rtp_settings.applescript").read_text()
        self.assertIn('Afficher le studio MIDI', source)
        self.assertIn('entire contents of toolbar 1', source)
        self.assertIn('help of candidateElement', source)
        self.assertIn('click networkButton', source)
        self.assertIn('perform action "AXPress" of networkButton', source)
        self.assertIn('static text "Sessions et répertoires"', source)
        self.assertNotIn('navigateur de périphériques réseau', source.lower())

    def test_peer_listing_excludes_the_local_rtp_session(self):
        source = (TOOLS / "list_rtp_peers.applescript").read_text()
        self.assertIn('Nom de réseau', source)
        self.assertIn('peerName is not localNetworkName', source)
        self.assertIn('"SELF\\t"', source)
        self.assertIn('"PEER\\t"', source)

    def test_legacy_reconnect_never_disconnects_an_unknown_session(self):
        source = (TOOLS / "reconnect_legacy_rtp.applescript").read_text()
        self.assertIn('set sessionCheckbox to UI element 1 of sessionContents', source)
        self.assertIn('set connectButton to UI element 3 of directoryGroup', source)
        self.assertIn('if activeName is connectedName then return "already-connected:"', source)
        self.assertNotIn('click button "Se déconnecter"', source)


if __name__ == "__main__":
    unittest.main()
