const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const source=fs.readFileSync('static/remote-v2.js','utf8');
const start=source.indexOf('  const LTC_PLACEHOLDER');
const end=source.indexOf('  const sharedLtcTimecode');
let now=0,tick;
const context={window:{setInterval(fn){tick=fn;}},document:{hidden:false},performance:{now:()=>now}};
vm.runInNewContext(source.slice(start,end),context);
const element={textContent:'',closest:()=>null};
const ltc=context.window.CLRemoteLTC;
ltc.enableSmoothing(element,25);
ltc.render(element,{ltc_connected:true,ltc_timecode:'01:02:03:00',is_playing:true});
now=120;tick();assert.equal(element.textContent,'01:02:03:03');
ltc.render(element,{ltc_connected:true,ltc_timecode:'01:02:03:04',is_playing:false});
now=1000;tick();assert.equal(element.textContent,'01:02:03:04');
ltc.render(element,{ltc_connected:true,ltc_timecode:'02:00:00:00',is_playing:true});
now=1040;tick();assert.equal(element.textContent,'02:00:00:01');
ltc.render(element,{ltc_connected:false,is_playing:true});
now=2000;tick();assert.equal(element.textContent,'--:--:--:--');
console.log('PASS: LTC advances during playback, freezes on stop, follows seeks and clears on disconnect.');
